apiVersion: v2
name: theidserver
description: TheIdServer cluster Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 4.6.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
appVersion: 4.5.1

# The list of keywords about this project
keywords:
  - oidc
  - openid-connect
  - oauth
  - identityserver
  - admin-ui
  - iam
  - sso

# The URL of this projects home page
home: https://github.com/Aguafrommars/TheIdServer

# The list of URLs to source code for this project
sources:
  - https://github.com/Aguafrommars/TheIdServer
  - https://github.com/Aguafrommars/helm/tree/main/charts/theidserver

# The list of maintenair for this project
maintainers:
  - name: Olivier Lefebvre
    email: aguacongas@gmail.com
    url: https://github.com/aguacongas

icon: https://raw.githubusercontent.com/Aguafrommars/TheIdServer/master/package-icon.png

dependencies:
  - name: mysql
    repository: https://charts.bitnami.com/bitnami
    version: 8.8.26
    condition: mysql.enabled, global.mysql.enabled
    tags:
      - back-end
      - mysql
    import-values:
      - child: service
        parent: mysql.service
  - name: seq
    repository: https://helm.datalust.co
    version: 2021.4.7192
    condition: seq.enabled, global.seq.enabled
    tags:
      - back-end
      - seq
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 16.5.2
    condition: redis.enabled, global.redis.enabled
    tags:
      - back-end
      - redis
