# Default values for TheIdServer.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Dependencies to install
tags:
  redis: true
  seq: true
  mysql: true

# Dependencies configuration
seq:
  image:
    tag: 2020.3

# Kestrel servers cerificates
ssl: 
  create: false
  cn:
  ipList: []
  sanList: []
  crt:
  key:

# Certificate to crypt data protection keys
dataProtection:
  create: false
  cn:
  ipList: []
  sanList: []
  crt:
  key:

# Certificate to crypt signing keys
signingKey:
  create: false
  cn:
  ipList: []
  sanList: []
  crt:
  key:
