{{- if and .Values.ssl.issuer.enabled -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "theidserver.fullname" . }}-cr
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
spec: 
  secretName: {{ include "theidserver.fullname" . }}-certs
  duration: {{ .Values.ssl.issuer.duration }}
  renewBefore: {{ .Values.ssl.issuer.renewBefore }}
  subject:
    organizations: 
    - {{ default (include "theidserver.fullname" .) .Values.ssl.cn | quote }}
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
  - server auth
  - client auth
  dnsNames:
  {{- range .Values.ingress.hosts }}
  - {{ .host | quote }}
  {{- end }}
  ipAddresses:
  {{- range .Values.ssl.ipList }}
  - {{ .host | quote }}
  {{- end }}
  issuerRef:
    name: {{ .Values.ssl.issuer.ref }}
    kind: {{ .Values.ssl.issuer.kind }}
{{- end -}}
