{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theidserver.fullname" . }}-certs
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.ssl.create }}
  {{- $issuer := default (printf "%s CA" (include "theidserver.fullname" .)) .Values.ssl.ca.issuer }}
  {{- $ca := genCA $issuer (default 3650 (int .Values.ssl.ca.validationPeriod)) }}
  {{- if not .Values.ssl.ca.create }}
  {{- $ca = buildCustomCert .Values.ssl.ca.crt .Values.ssl.ca.key }}
  {{- end }}
  {{- $cn := default (include "theidserver.fullname" .) .Values.ssl.cn }}
  {{- $altNames := list $cn (printf "%s:%d" $cn (int .Values.service.ports.https)) "localhost" (printf "localhost:%d" (int .Values.service.ports.https)) }}
  {{- if .Values.ingress.enabled }}
  {{- range .Values.ingress.hosts }}
  {{- $altNames = mustAppend $altNames .host }}
  {{- $altNames = mustAppend $altNames (printf "%s:%d" .host (int $.Values.service.ports.https)) }}
  {{- end }}
  {{- end }}
  {{- $ipList := list "127.0.0.1" }}
  {{- $server := genSignedCert $cn (default $ipList .Values.ssl.ipList) (default $altNames .Values.ssl.sanList) (default 365 (int .Values.ssl.validationPeriod)) $ca }}
  ssl.crt: {{ $server.Cert | b64enc }}
  ssl.key: {{ $server.Key | b64enc }}
  ca.crt: {{ $ca.Cert | b64enc }}
  ca.key: {{ $ca.Key | b64enc }}
  {{- else }}
  ssl.crt: {{ required "ssl.crt is required" .Values.ssl.crt }}
  ssl.key: {{ required "ssl.key is required" .Values.ssl.key }}
  {{- if .Values.ssl.ca.trust }}
  ca.crt: {{ required "ssl.ca.crt is required" .Values.ssl.ca.crt }}
  ca.key: {{ required "ssl.ca.key is required" .Values.ssl.ca.key }}
  {{- else }}
  ca.crt: {{ .Values.ssl.ca.crt }}
  ca.key: {{ .Values.ssl.ca.key }}  
  {{- end }}
  {{- end }}
  {{- if and .Values.dataProtection.create (not .Release.IsUpgrade) }}
  {{- $ca := genCA ( include "theidserver.fullname" . ) 365 }}
  {{- $cn := default .Release.Namespace .Values.dataProtection.cn }}
  {{- $server := genSignedCert $cn ( default nil .Values.dataProtection.ipList ) ( default nil .Values.dataProtection.sanList ) 365 $ca }}
  dataProtection.crt: {{ $server.Cert | b64enc }}
  dataProtection.key: {{ $server.Key | b64enc }}
  {{- else }}
  dataProtection.crt: {{ required "dataProtection.crt is required when dataProtection.create is false or for an upgrade" .Values.dataProtection.crt }}
  dataProtection.key: {{ required "dataProtection.key is required when dataProtection.create is false or for an upgrade" .Values.dataProtection.key }}
  {{- end }}
  {{- if and .Values.signingKey.create (not .Release.IsUpgrade) }}
  {{- $ca := genCA ( include "theidserver.fullname" . ) 365 }}
  {{- $cn := default .Release.Namespace .Values.signingKey.cn }}
  {{- $server := genSignedCert $cn ( default nil .Values.signingKey.ipList ) ( default nil .Values.signingKey.sanList ) 365 $ca }}
  signingKey.crt: {{ $server.Cert | b64enc }}
  signingKey.key: {{ $server.Key | b64enc }}
  {{- else }}
  signingKey.crt: {{ required "signingKey.crt is required when signingKey.create is false or for an upgrade" .Values.signingKey.crt }}
  signingKey.key: {{ required "signingKey.key is required when signingKey.create is false or for an upgrade" .Values.signingKey.key }}
  {{- end }}
{{- end -}}