apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theidserver.fullname" . }}-config
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
data:
  {{- if .Values.redis.enabled }}
  SignalR__RedisConnectionString: "{{ include "theidserver.redis" . }}"
  {{- end }}
  {{- if .Values.seq.enabled }}
  Serilog__WriteTo__0__Args__serverUrl: "{{ include "theidserver.seqUrl" . }}"
  {{- end }}
  {{- range $key, $value := .Values.appSettings.env }}
  {{ $key }}: {{ $value |quote }}
  {{- end }}
  ASPNETCORE_URLS: "https://+:{{ required "service.ports.https is required" .Values.service.ports.https }}"
  ASPNETCORE_HTTPS_PORT: "{{ required "service.ports.https is required" .Values.service.ports.https }}"
  ASPNETCORE_Kestrel__Certificates__Default__Path: "/usr/local/share/ca-certificates/ssl.pfx"
  IdentityServer__Key__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/sk.pfx
  DataProtectionOptions__KeyProtectionOptions__X509CertificatePath: /usr/local/share/ca-certificates/dp.pfx
