{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "theidserver.fullname" . }}-config-files
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
data:
  admin-appsettings.json: {{ tpl (.Files.Get "admin-appsettings.json") . | quote }}
{{- end -}}