{{- if .Values.ingress.enabled -}}
{{- $fullName := include "theidserver.fullname" . -}}
{{- $port := .Values.service.ports.https -}}
{{- $gitVersion := .Capabilities.KubeVersion.GitVersion -}}
{{- if semverCompare ">=1.19-0" $gitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" $gitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- if semverCompare ">=1.19-0" $gitVersion }}
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $port }}
        {{- else -}}
          - backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $port }}
        {{- end }}
    {{- end }}
{{- end }}
