apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theidserver.fullname" . }}-opaque
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
data:
  tls.pwd: {{ uuidv4 | b64enc }}
  dataProtection.pwd: {{ uuidv4 | b64enc }}
  signingKey.pwd: {{ uuidv4 | b64enc }}
type: Opaque
