apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theidserver.fullname" . }}-opaque
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
data:
  ConnectionString: {{ include "theidserver.connectionString" . | b64enc }}  
  ssl.pwd: {{ uuidv4 | b64enc }}
type: Opaque
