{{- if .Values.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "theidserver.fullname" . }}-opaque
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
data:
  {{- if not .Values.appSettings.Proxy }}
  ConnectionString: {{ include "theidserver.connectionString" . | b64enc }}
  {{- end }}
  ssl.pwd: {{ uuidv4 | b64enc }}
  dataProtection.pwd: {{ uuidv4 | b64enc }}
  signingKey.pwd: {{ uuidv4 | b64enc }}
type: Opaque
{{- end -}}