{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "theidserver.fullname" . }}
  labels:
    {{- include "theidserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $value := .Values.service.ports }}
    - port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end }}
  selector:
    {{- include "theidserver.selectorLabels" . | nindent 4 }}
{{- end -}}