apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "private.fullname" . }}-config-files
  labels:
    {{- include "private.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "*.json").AsConfig | indent 2 }}