name: Publish Charts to gh-pages
on:
  push:
    branches: [ master ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Package and Publish charts
      uses: J12934/helm-gh-pages-action@master
      with:
        deploy-branch: gh-pages
        access-token: "${{ secrets.CR_TOKEN }}"
